# syntax = docker/dockerfile:experimental
FROM ...

COPY get_build_secret.sh .
RUN --mount=type=secret,id=build_secret ./get_build_secret.sh


# get_build_secret.sh
#!/bin/bash
# set -euo pipefail
# if [ -f /run/secrets/build_secret ]; then
#    export BUILD_SECRET=$(cat /run/secrets/build_secret)
# fi

# foo install < which uses the BUILD_SECRET >
